language: node_js

sudo: false

cache:
  apt: true
  directories:
    - node_modules

node_js:
  - "7"
  - "8"

script:
  - npm test

after_script:
  - npm install -g codecov
  - cat ./coverage/lcov.info | codecov
